# Generated by Django 2.1.5 on 2019-02-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belongschool',
            name='art_or_science',
            field=models.CharField(choices=[('A', 'Art'), ('S', 'Science')], max_length=1),
        ),
    ]
