# Generated by Django 2.1.5 on 2019-02-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hr_app', '0002_auto_20190204_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belongschool',
            name='concentration',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='belongschool',
            name='department',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
