# Generated by Django 2.1.5 on 2019-02-04 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hr_app', '0003_auto_20190204_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belongschool',
            name='deviation',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
